mongodb:
  uri: "mongodb://localhost:27017"
  database: "statemachines"

server:
  port: 8080

redis:
  host: "localhost"
  port: 6379

kafka:
  bootstrapServers: "localhost:9092"
  groupId: "order-group"
  topic: "abc"

