mongodb:
  uri: "mongodb+srv://shubham:aWIxhLUDPc19Reet@staging3.fj9ko.mongodb.net/"
  database: "payexQA"

server:
  port: 8080

redis:
  host: "localhost"
  port: 6379

kafka:
  bootstrapServers: "localhost:9092"
  groupId: "order-group"
  topic: "abc"

